### ISSUE TITLE
Bug: Tras salir de la tienda no se hace de día.

### ISSUE THREAD

**Issue by MartaVidal** [S-pain-Games/Cookie-Quest-Maker#8]
Impacto: Alto

Plataforma: PC (no se ha podido replicar así que no es posible confirmar si ocurre también en dispositivos móviles)

Descripción: Tras salir de la tienda no se hace de día, el jugador se queda atrapado en un bucle en la noche. Es posible hablar de nuevo con Evith y esta vuelve a abrir la tienda, pero al cerrarla sigue sin continuar el flujo del juego.

Pasos para reproducir: no se ha conseguido replicar.

**Comment by CarlosMariano05** [comment]
A mi también me ha pasado. No soy capaz de salir de esa noche aunque puedo hablar con Evith todas las veces que quiera. 

Estoy usando google chrome para pc y sale lo siguiente en la consola. 
e4ad55ff-0e9c-4a42-ac0f-7dc636c548bc:2 KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in <00000000000000000000000000000000>:0 

Pasos para reproducirlo: solo sé que ha sido después de la misión principal de la sociedad de ratas de El Mantecas. Pero no la noche inmediata, una de las noches siguientes.

**Comment by Anthonys-source** [comment]
Hemos encontrado el fallo y lo hemos solucionado, ya se debería poder terminar el juego
